### ISSUE TITLE
Drag & Drop: Add "AllowDrag" attached propeties

### ISSUE THREAD

**Issue by nazarenomanco** [RadicalFx/radical#153] opened 2015-05-25 11:16 UTC
Adding a boolean "AllowDrag" attached propeties will allow to disable starting drag operation from some controls.

--

Depends on #154

**Comment by mauroservienti** [comment] 2015-05-25 11:25
Depends on #154

**Comment by mauroservienti** [comment] 2015-05-25 15:27
Closing as duplicate of #151

**Closed by mauroservienti** 2015-05-25 15:27 UTC
